### ISSUE TITLE
Miner doesn´t recognize files in folder

### ISSUE THREAD

**Issue by Zarrsito** [signum-network/signum-miner#15]
Hello, i wanna setup a 2nd miner in my house (QNAP NAS), i have some old hdd´s with plotfiles on them and want to reactivate those =)
so i setup the miner on my NAS but unfortunaly the miner doesnt access the files or whatever is wrong..
so this is an ARM NAS , QNAP TS-932PX , 
i have an USB Tray also QNAP-TR004 with 4 hdd´s filled with plotfiles
and i own an QNAP-TS451, on this NAS im actually Mining with around 28TB HDD / 14TB inside and 14TB on the TR004
so i´ve added hdds to the TS-932PX containing plotfiles , i can see them (as shown in the screenshot) but the Miner does not....
i can connect the TR004 to the 932PX , and i can see the files but the Miner not.....

Any Advice?!?!?

The TS-932PX is running on an Linux 4.2.8 Kernel (ARM)
The TS-451 is running on an Linux 5.10 Kernel (Intel CPU)
both NAS have the same Distro (QTS-5.5)

[/share/CACHEDEV2_DATA/scavenger] # uname -m
aarch64
[/share/CACHEDEV2_DATA/scavenger] # uname -n
QNAP-TS932PX
[/share/CACHEDEV2_DATA/scavenger] # uname -r
4.2.8
[/share/CACHEDEV2_DATA/scavenger] # uname -s
Linux
[/share/CACHEDEV2_DATA/scavenger] # uname -p
unknown                  -                 [AnnapurnaLabs Alpine AL-324 ARM® Cortex-A57 4-Core 1,7GHz Prozessor]
[/share/CACHEDEV2_DATA/scavenger] # uname -v
#1 SMP Mon Feb 19 14:36:11 CST 2024
[/share/CACHEDEV2_DATA/scavenger] # uname -i
unknown
[/share/CACHEDEV2_DATA/scavenger] # uname -o
GNU/Linux

--------LOG--------

14:21:01 [INFO]  signum-miner v.1.8.0
14:21:01 [INFO]  SIMD extensions: NEON
14:21:01 [INFO]  path=/share/CACHEDEV2_DATA/BurstPlots, files=0, size=0.0000 TiB
14:21:01 [WARN]  no plots in /share/CACHEDEV2_DATA/BurstPlots
14:21:01 [INFO]  path=/share/CACHEDEV4_DATA/BurstPlots_2, files=0, size=0.0000 TiB
14:21:01 [WARN]  no plots in /share/CACHEDEV4_DATA/BurstPlots_2
14:21:01 [INFO]  plot files loaded: total drives=0, total capacity=0.0000 TiB
14:21:01 [INFO]  reader-threads=0 CPU-threads=4
14:21:01 [INFO]  CPU-buffer=4(+4)
14:21:01 [INFO]  new block: height=1261499, scoop=3383

--------SCREENSHOT--------

![image](https://github.com/signum-network/signum-miner/assets/78433597/deca23bd-2a30-4ae7-a33d-5319f0426e09)

--------CONFIG.YAML--------

plot_dirs:
   - '/share/CACHEDEV8_DATA/NVIDIA'    -- here i copied the First Plot file generated... i thought maybe to initialize the miner?!
   - '/share/CACHEDEV2_DATA/BurstPlots'
   - '/share/CACHEDEV4_DATA/BurstPlots_2'

url: 'http://192.168.2.30:8125/'      # solo mining with local wallet

hdd_reader_thread_count: 0            # default 0 (=auto: number of disks)
hdd_use_direct_io: true               # default true
hdd_wakeup_after: 0                   # default 240s

cpu_threads: 0                        # default 0 (=auto: number of logical cpu cores)
cpu_worker_task_count: 4              # default 4 (0=GPU only)
cpu_nonces_per_cache: 65536           # default 65536
cpu_thread_pinning: false             # default false

gpu_threads: 0                        # default 0 (=GPU off)
gpu_platform: 0                       # default 0
gpu_device: 0                         # default 0
gpu_worker_task_count: 0              # default 0 (=CPU only)
gpu_nonces_per_cache: 262144          # default 262144
gpu_mem_mapping: false                # default false
gpu_async: false                      # default false

target_deadline: 750514               # default 31536000 (1 year)
account_id_to_target_deadline:        # target dls for multi-id (optional)
 
 
get_mining_info_interval: 3000        # default 3000ms
timeout: 5000                         # default 5000ms
send_proxy_details: true              # default false
submit_only_best: true                # default true
#additional_headers:                  # add/overwrite html header
#  "AccountKey" : "1234567890"

console_log_level: 'info'             # default Info, options (off, error, warn, info, debug, trace)
logfile_log_level: 'warn'             # default Warn, options (off, error, warn, info, debug, trace)
logfile_max_count: 10                 # maximum number of log files to keep
logfile_max_size : 20                 # maximum size per logfile in MiB

show_progress: true                   # default true  
show_drive_stats: true                # default false 
benchmark_only: 'disabled'            # default disabled, options (disabled, I/O, XPU)

# Low noise log patterns
console_log_pattern: "{({d(%H:%M:%S)} [{l}]):16.16} {m}{n}"
logfile_log_pattern: "{({d(%Y-%m-%d %H:%M:%S)} [{l}]):26.26} {m}{n}"

# More detailed log patterns
#console_log_pattern: "{d(%H:%M:%S.%3f%z)} [{h({l}):<5}] [{T}] [{t}] - {M}:{m}{n}"
#logfile_log_pattern: "{d(%Y-%m-%dT%H:%M:%S.%3f%z)} [{h({l}):<5}] [{T}]-[{t}] [{f}:{L}] - {M}:{m}{n}"

**Comment by pir8radio** [comment]
What did you find? Might help someone else.

**Comment by Zarrsito** [comment]
well, i did several things with support from the discord channel, it seems RPi and QNAP related bugs due to cut linux versions
