### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by abdulaleem13** [signum-network/signum-miner#7]
not working on more than 1010 plots.

![Screenshot from 2021-07-10 06-40-11](https://user-images.githubusercontent.com/12502568/125161967-08b7eb80-e14b-11eb-83ce-82e9ec23b644.png)

**Comment by jjos2372** [comment]
Hello, this might be a system wide limitation and not related directly to signum-miner. Please check if the instructions here can help you in that case: https://www.tecmint.com/increase-set-open-file-limits-in-linux/

**Comment by abdulaleem13** [comment]
Worked with command ulimit -n 2024 for current session. Files limit increased from 1024 to 2024. Thanks
